services:
  postgres:
    image: postgres:latest
    container_name: future_appointments_postgres
    restart: always
    environment:
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: belcher
      POSTGRES_DB: future_appointments
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    # image: golang:1.23-alpine
    image: cosmtrek/air
    container_name: future-take-home
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      GIN_MODE: release
      DATABASE_URL: postgres://bob:belcher@postgres:5432/future_appointments?sslmode=disable
    command: sh -c "go mod download && go run main.go"

volumes:
  postgres_data:
    driver: local
