services:
  api:
    image: golang:1.23-alpine
    container_name: future-take-home
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    command: sh -c "go mod download && go run main.go"
    labels:
      - "orbstack.domain=future.orb.local"
